In [7]:
import numpy as np

In [8]:
age = np.array([24,23,27,29])
age

array([24, 23, 27, 29])

In [9]:
print(age)
type(age)

[24 23 27 29]


numpy.ndarray

In [10]:
age.ndim

1

In [11]:
age_1 = np.array([[24],[23],[27],[29]])
age_1

array([[24],
       [23],
       [27],
       [29]])

In [12]:
age_1.ndim

2

In [13]:
data = np.array([[24,170,58],[23,168,52],[27,172,61],[29,156,45]])
data

array([[ 24, 170,  58],
       [ 23, 168,  52],
       [ 27, 172,  61],
       [ 29, 156,  45]])

In [14]:
data.shape

(4, 3)

In [15]:
# Rows and Column
data[:,0:1]

array([[24],
       [23],
       [27],
       [29]])

In [16]:
data[:,1:3]

array([[170,  58],
       [168,  52],
       [172,  61],
       [156,  45]])

In [17]:
data[1:3,0:1]

array([[23],
       [27]])

In [18]:
d = data[:,0:1]
d

array([[24],
       [23],
       [27],
       [29]])

In [19]:
print("Mean: ",np.mean(d))

Mean:  25.75


In [20]:
print("Median: ",np.median(d))

Median:  25.5


In [21]:
print("Mode: ",np.mode(d))

AttributeError: module 'numpy' has no attribute 'mode'

In [22]:
print("Standard Deviation: ",np.std(d))

Standard Deviation:  2.384848003542364


In [23]:
print("Variance: ",np.var(d))

Variance:  5.6875


In [24]:
print("Minimum: ",np.min(d))

Minimum:  23


In [25]:
print("Maximum: ",np.max(d))

Maximum:  29


In [26]:
np.random.random(10) # print numbers from 0 to 1

array([0.68870708, 0.90170873, 0.83079985, 0.16158686, 0.17036524,
       0.14434685, 0.55895882, 0.90730029, 0.6063741 , 0.9248878 ])

In [27]:
np.random.random(5) # print numbers from 0 to 1

array([0.28781611, 0.72830801, 0.29164296, 0.26126   , 0.04206083])

In [28]:
r1 =np.random.randint(10,40,size = 5)
r1

array([31, 12, 22, 27, 18])

In [29]:
r1.ndim

1

In [30]:
r2 =np.random.randint(10,40,size = (2,5))
r2

array([[25, 26, 32, 19, 31],
       [14, 27, 39, 37, 24]])

In [31]:
r2.ndim

2

In [33]:
r3 =np.random.randint(10,40,size = (2,2,5))
r3

array([[[21, 14, 24, 25, 35],
        [18, 20, 32, 23, 11]],

       [[35, 21, 28, 33, 39],
        [13, 38, 24, 25, 28]]])

In [34]:
r3.ndim

3

In [35]:
lucky_draw = np.random.randint(1000,9999, size = 1)
lucky_draw

array([9325])

In [36]:
data 

array([[ 24, 170,  58],
       [ 23, 168,  52],
       [ 27, 172,  61],
       [ 29, 156,  45]])

In [37]:
import pandas as pd
df = pd.DataFrame(data)
df

0    1   2
0  24  170  58
1  23  168  52
2  27  172  61
3  29  156  45

In [38]:
df.columns = ["age","height","weight"]
df

age  height  weight
0   24     170      58
1   23     168      52
2   27     172      61
3   29     156      45

In [39]:
df.index = ["a","b","c","d"]
df

age  height  weight
a   24     170      58
b   23     168      52
c   27     172      61
d   29     156      45

In [40]:
df.age

a    24
b    23
c    27
d    29
Name: age, dtype: int32

In [41]:
a1 = df["age"]
a1

a    24
b    23
c    27
d    29
Name: age, dtype: int32

In [42]:
print("Mean: ",a1.mean())
print("Median: ",a1.median())
print("Mode: ",a1.mode())
print("Std: ",a1.std())
print("Var: ",a1.var())
print("Min: ",a1.min())
print("Max: ",a1.max())

Mean:  25.75
Median:  25.5
Mode:  0    23
1    24
2    27
3    29
Name: age, dtype: int32
Std:  2.753785273643051
Var:  7.583333333333333
Min:  23
Max:  29


In [43]:
df["age"].describe()

count     4.000000
mean     25.750000
std       2.753785
min      23.000000
25%      23.750000
50%      25.500000
75%      27.500000
max      29.000000
Name: age, dtype: float64

In [44]:
df.describe()

age      height     weight
count   4.000000    4.000000   4.000000
mean   25.750000  166.500000  54.000000
std     2.753785    7.187953   7.071068
min    23.000000  156.000000  45.000000
25%    23.750000  165.000000  50.250000
50%    25.500000  169.000000  55.000000
75%    27.500000  170.500000  58.750000
max    29.000000  172.000000  61.000000