# Section A: Data Structures & Control Structures

Q1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
# List Operations in Python

# 1. Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# 2. Append - add a single element at the end
numbers.append(60)
print("After append(60):", numbers)

# 3. Extend - add multiple elements at the end
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# 4. Insert - add an element at a specific index
numbers.insert(2, 25)  # insert 25 at index 2
print("After insert(2, 25):", numbers)

# 5. Remove - remove first occurrence of a value
numbers.remove(40)  # removes 40
print("After remove(40):", numbers)

# 6. Pop - remove element at given index (or last element if no index)
popped_value = numbers.pop(3)  # remove element at index 3
print(f"After pop(3): {numbers}, Popped value: {popped_value}")

# 7. Index - find the index of first occurrence of a value
index_value = numbers.index(25)
print("Index of 25:", index_value)

# 8. Count - count occurrences of a value
count_value = numbers.count(20)
print("Count of 20:", count_value)

# 9. Sort - sort list in ascending order
numbers.sort()
print("After sort():", numbers)

# 10. Reverse - reverse the list order
numbers.reverse()
print("After reverse():", numbers)

# 11. Clear - remove all elements from list
numbers.clear()
print("After clear():", numbers)

Original List: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(3): [10, 20, 25, 50, 60, 70, 80], Popped value: 30
Index of 25: 2
Count of 20: 1
After sort(): [10, 20, 25, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 25, 20, 10]
After clear(): []


Q2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
# Creating a tuple with 3 student names
students = ("Amit", "Priya", "Rohan")
print("Original tuple:", students)

# Trying to change the 2nd element (index 1)
try:
    students[1] = "Neha"  # Attempt to modify tuple
except TypeError as e:
    print("Error:", e)

Original tuple: ('Amit', 'Priya', 'Rohan')
Error: 'tuple' object does not support item assignment


Explanation:
1. Tuples in Python are immutable, meaning once created, their elements cannot be changed (no assignment, removal, or insertion).
2. That’s why when you try to replace "Priya" with "Neha", Python raises a TypeError.
3. If you need a collection where elements can be changed, you should use a list instead.

Q3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
# Creating a set with duplicate values
numbers = {10, 20, 30, 20, 40, 10, 50}

# Print the set
print("Set contents:", numbers)

Set contents: {50, 20, 40, 10, 30}


Explanation:
1. Sets in Python automatically remove duplicates. Even though we wrote 10 and 20 multiple times, they appear only once in the set.
2. Sets are unordered collections. The order of elements is not guaranteed (may vary each time you run the program).

Q4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
# Creating a dictionary
student = {
    "name": "Kaustubh",
    "age": 20,
    "city": "Thane"
}
print("Original dictionary:", student)

# Update the age
student["age"] = 21

# Add a new key 'email'
student["email"] = "kaustubhjadhavrj@gmail.com"

# Print the final dictionary
print("Updated dictionary:", student)

Original dictionary: {'name': 'Kaustubh', 'age': 20, 'city': 'Thane'}
Updated dictionary: {'name': 'Kaustubh', 'age': 21, 'city': 'Thane', 'email': 'kaustubhjadhavrj@gmail.com'}


Q5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:
# Take age as input
age = int(input("Enter your age: "))

# Check eligibility
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

Enter your age:  20


You are eligible to vote.


## Q6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [6]:
# Take marks as input
marks = int(input("Enter marks: "))

# Check grade conditions
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"

# Print result
print(f"Marks: {marks}, Grade: {grade}")

Enter marks:  87


Marks: 87, Grade: B


Q7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
# Take input from user
num = int(input("Enter a number: "))

# Check conditions
if num > 0:
    if num % 2 == 0:
        print(f"{num} is positive and even.")
    else:
        print(f"{num} is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print(f"{num} is negative.")

Enter a number:  5


5 is positive but odd.


# Section B: Numpy

Q8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [8]:
import numpy as np

# 1. Scalar using np.array
scalar = np.array(5)
print("Scalar:", scalar)
print("Dimension of scalar:", scalar.ndim)

# 2. 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:", array_1d)

# 3. 2D array (2x3) with values 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("\n2D Array (2x3):\n", array_2d)

Scalar: 5
Dimension of scalar: 0

1D Array: [1 2 3 4 5]

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


Q9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [9]:
import numpy as np

# Generate 4x4 array of random integers from 0 to 100
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:\n", random_array)

4x4 Random Array:
 [[98 89 84 30]
 [79 53 38  6]
 [54 78 34 34]
 [76 26  2 37]]


Q10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [10]:
import numpy as np
import pandas as pd

# 1. Create a 2D NumPy array of shape (3x3)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
print("2D NumPy Array:\n", array_2d)

# 2. Convert it into a Pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])
print("\nPandas DataFrame with column names:\n", df)

2D NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Pandas DataFrame with column names:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


# Section C: Exploring Pandas

Q11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [11]:
import pandas as pd
import numpy as np

# 1. Create a DataFrame manually with 10 rows
data = {
    'Name': ['Amit', 'Priya', 'Rohan', 'Neha', 'Anil', 'Priya', 'Kiran', 'Rohan', 'Sita', 'Amit'],
    'Age': [25, 30, 28, 22, 35, 30, 27, 28, 26, 25],
    'City': ['Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Delhi', 'Pune', 'Pune', 'Mumbai', 'Mumbai'],
    'Salary': [50000, 60000, np.nan, 45000, 70000, 60000, 48000, np.nan, 52000, 50000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# 2. Use .info() and .describe()
print("\nDataFrame Info:")
print(df.info())

print("\nDataFrame Describe:")
print(df.describe())

# 3. Select 'Name' and 'City' columns
print("\nSelected Columns (Name and City):")
print(df[['Name', 'City']])

# 4. Drop 'City' column
df_dropped = df.drop('City', axis=1)
print("\nDataFrame after dropping 'City' column:\n", df_dropped)

# 5. Fill missing values in 'Salary' with the mean
mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\nDataFrame after filling missing Salary values:\n", df)

# 6. Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)

Original DataFrame:
     Name  Age    City   Salary
0   Amit   25  Mumbai  50000.0
1  Priya   30   Delhi  60000.0
2  Rohan   28    Pune      NaN
3   Neha   22  Mumbai  45000.0
4   Anil   35   Delhi  70000.0
5  Priya   30   Delhi  60000.0
6  Kiran   27    Pune  48000.0
7  Rohan   28    Pune      NaN
8   Sita   26  Mumbai  52000.0
9   Amit   25  Mumbai  50000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame Describe:
             Age        Salary
count  10.000000      8.000000
mean   27.600000  54375.000000
std     3.565265   8279.708414
min    22.000000  45000.000000
25%    25.250000  49500.000000
50%    27.500000  5

C:\Users\Kaustubh Jadhav\AppData\Local\Temp\ipykernel_22652\2805236277.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)
